apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "Hello world site 1!";
       }
   }
}
'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: config-vol
            mountPath: /etc/nginx/
      volumes:
        - name: config-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
---				
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
spec:
  type: NodePort 
  ports:
  - port: 82
    targetPort: 80
  selector:
    app: nginx-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "Hello world site 2!";
       }
   }
}
'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx:latest
        name: nginx-2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: config-vol-2
            mountPath: /etc/nginx/
      volumes:
        - name: config-vol-2
          configMap:
            name: nginx-config-2
            items:
              - key: nginx.conf
                path: nginx.conf
